# Generated by Django 2.2.13 on 2020-06-29 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Наименование модуля', max_length=180, verbose_name='Наименование модуля')),
                ('description', models.TextField(default='Описание модуля', max_length=10000, verbose_name='Описание')),
                ('shortDescription', models.TextField(default='Короткое описание модуля', max_length=300, verbose_name='Короткое описание')),
                ('pictogram', models.ImageField(height_field=76, upload_to='', verbose_name='Пиктограмма 75Х75', width_field=76)),
                ('promoPictogram', models.ImageField(height_field=301, upload_to='', verbose_name='Промо Изображение 300х300', width_field=301)),
                ('isEnabled', models.BooleanField(default=False)),
                ('serverURL', models.URLField(default='localhost:7000', verbose_name='Сыль на модуль')),
                ('availableUsers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
